title: WDS Components Library
description: >
  The WDS Components Library is a collection of WordPress-ready components that can be dropped into any WordPress project. The WDS Components Library works really great with our starter theme wd_s, but can be used with any WordPress theme.
url: https://WebDevStudios.github.io
baseurl: /wds-components-library
author:
  name: WebDevStudios
  email: contact@webdevstudios.com
  website: https://webdevstudios.com
  github: webdevstudios
  twitter: webdevstudios
markdown: kramdown
sass:
  sass_dir: assets/styles/scss
collections:
  components:
    output: true
  colors:
    output: false
  fonts:
    output: false
  categories:
    output: false
